model:
    model_id: "opensora"
    model_type: 'opensora'  # ['sd','sdxl']
calib_data:
weight:
  n_bits: 8
  group: 'tensor'
  sym: True
act:
  n_bits: 8
  group: 'token' # DIRTY: it is not used, forced as "token-wise"
  sym: True
remain_fp_regex: embedder|adaLN_modulation|t_block

