model:
    model_id: "opensora"
    model_type: 'opensora'  # ['sd','sdxl']
remain_fp_regex: embedder|adaLN_modulation|final_layer|t_block
# quarot:
#   layer_name_regex: mlp
mixed_precision:  # the unmentioned layers are remained the main bitwidth (n_bits[i_bitwidth])
  weight:
    layer_name_regex: ['embedder|adaLN_modulation|final_layer|t_block|cross','','11|12|13|14','mlp']  # [FP, [n_bits]]
  act:
    layer_name_regex: ['embedder|adaLN_modulation|final_layer|t_block|cross','','11|12|13|14','mlp']
# smooth_quant:
#   alpha: 0.8
#   layer_name_regex: cross_attn.q_linear
viditq:
  alpha: 0.5665
  layer_name_regex: 11|12|13|14
calib_data:
  save_path: ./calib_data.pth
weight:
  n_bits: [2,4,8]
  i_bitwidth: 2
  sym: False
act:
  n_bits: [2,4,8]
  i_bitwidth: 2
  sym: True